services:
  postgres:
    image: postgres
    container_name: dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # code-server:
  #   image: lscr.io/linuxserver/code-server:latest
  #   container_name: code-server
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #     - PASSWORD=password #optional
  #     - HASHED_PASSWORD= #optional
  #     - SUDO_PASSWORD=password #optional
  #     - SUDO_PASSWORD_HASH= #optional
  #     - PROXY_DOMAIN=code-server.my.domain #optional
  #     - DEFAULT_WORKSPACE=/config/workspace #optional
  #   volumes:
  #     - ./code-server/config:/config
  #   ports:
  #     - 2000:8443
  #   restart: unless-stopped
